### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by nknr** [abhinav0612/CineWatch#1]
MoviesDirections fragment and Utils package

![Annotation 2020-07-22 095934](https://user-images.githubusercontent.com/18142767/88134401-0a07a580-cbd4-11ea-9448-d0156e70486d.png)

**Comment by bugcacher** [comment]
MovieDirections are Navigation Component generated file rebuild the project or go to the nav_graph.xml and check for the directions. As for the Constants file, it contains my TMDB key so I haven't uploaded that file you can generate yours from the TMDB website.
